import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
  HiArrowDownTray,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiDocker,
  SiBlender,
  SiGooglegemini,
  SiOllama,
  SiLinux,
  SiClaude,
  SiOpenai,
  SiN8N,
  SiAutodeskmaya,
  SiAdobephotoshop,
  SiAdobepremierepro,
  SiAdobeaftereffects,
  SiDavinciresolve,
} from "react-icons/si";

// Generic icons for tools without a published logo
import { LuWorkflow, LuClapperboard, LuMusic, LuCpu, LuPaintbrush, LuBrush } from "react-icons/lu";

import { FaDiscord, FaGithub, FaLinkedin, FaX, FaThreads, FaInstagram, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram, FaArtstation, FaYoutube, FaPhone } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
  artstation: FaArtstation,
  youtube: FaYoutube,
  phone: FaPhone,
  download: HiArrowDownTray,
  docker: SiDocker,
  blender: SiBlender,
  gemini: SiGooglegemini,
  ollama: SiOllama,
  linux: SiLinux,
  claude: SiClaude,
  openai: SiOpenai,
  n8n: SiN8N,
  maya: SiAutodeskmaya,
  photoshop: SiAdobephotoshop,
  premiere: SiAdobepremierepro,
  afterEffects: SiAdobeaftereffects,
  davinci: SiDavinciresolve,
  workflow: LuWorkflow,
  video: LuClapperboard,
  music: LuMusic,
  cpu: LuCpu,
  paintbrush: LuPaintbrush,
  brush: LuBrush,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
